// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwrxlAlDagYZ3BNHMvofcS07XH2Ar7Q6s',
    appId: '1:144543097486:web:3229802f60d85e21971fdf',
    messagingSenderId: '144543097486',
    projectId: 'mbti-test-flutter',
    authDomain: 'mbti-test-flutter.firebaseapp.com',
    storageBucket: 'mbti-test-flutter.firebasestorage.app',
    measurementId: 'G-9Z558726WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4TN3L1YX0ZTWzVvWFeNUwqPsEZkRiS7o',
    appId: '1:144543097486:android:ada36e96ca83838d971fdf',
    messagingSenderId: '144543097486',
    projectId: 'mbti-test-flutter',
    storageBucket: 'mbti-test-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfwvBy4QSFM5aT3KeCvvF4Q_nZ6iH-fbY',
    appId: '1:144543097486:ios:fee31effd13a1c1c971fdf',
    messagingSenderId: '144543097486',
    projectId: 'mbti-test-flutter',
    storageBucket: 'mbti-test-flutter.firebasestorage.app',
    iosBundleId: 'com.example.mbtiTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfwvBy4QSFM5aT3KeCvvF4Q_nZ6iH-fbY',
    appId: '1:144543097486:ios:fee31effd13a1c1c971fdf',
    messagingSenderId: '144543097486',
    projectId: 'mbti-test-flutter',
    storageBucket: 'mbti-test-flutter.firebasestorage.app',
    iosBundleId: 'com.example.mbtiTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwrxlAlDagYZ3BNHMvofcS07XH2Ar7Q6s',
    appId: '1:144543097486:web:d0e199a39122ded0971fdf',
    messagingSenderId: '144543097486',
    projectId: 'mbti-test-flutter',
    authDomain: 'mbti-test-flutter.firebaseapp.com',
    storageBucket: 'mbti-test-flutter.firebasestorage.app',
    measurementId: 'G-VEPNFQG33R',
  );
}
